name: cog_ai
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  # CUDA and GPU
  - cudatoolkit=12.1
  - cupy>=12.1.0
  - pynvml>=11.5.0
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  
  # Core Scientific
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.2.0
  
  # Development Tools
  - black
  - isort
  - flake8
  - mypy
  - pytest
  - pytest-cov
  - jupyter
  - ipykernel
  - nb_conda_kernels
  
  # System Monitoring
  - psutil
  - pip>=23.0
  
  - pip:
    # Additional packages not available in conda
    - structlog==23.2.0
    - prometheus-client==0.19.0
    - python-dotenv==0.19.0
    - sphinx==7.2.6
    - sphinx-rtd-theme==1.3.0
    - autodoc==0.5.0

variables:
  CUDA_HOME: "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1"
  PYTHONPATH: "${CONDA_PREFIX}\\Lib\\site-packages"
